//白⚪️,紫🟣,赤🔴,黄🟡,緑🟢
//ゲキだけじゃなくなったけどファイル名変えるのめんどいから放置



let song = [//	{ dev:"オンゲキ", con:, dif:"MASTER", tit:""},
{ dev:"オンゲキ",con:"15.7",dif:"MASTER",曲名:"🟣Recollect Lines"},
{ dev:"オンゲキ",con:"15.6",dif:"MASTER",曲名:"🟣μ3"},
{ dev:"オンゲキ",con:"15.4",dif:"MASTER",曲名:"🟣Apollo"},
{ dev:"オンゲキ",con:"15.4",dif:"MASTER",曲名:"🟣LAMIA"},
{ dev:"オンゲキ",con:"15.4",dif:"MASTER",曲名:"🟣Selenadia"},
{ dev:"オンゲキ",con:"15.4",dif:"MASTER",曲名:"🟣FestA of PandemoniuM"},
{ dev:"オンゲキ",con:"15.3",dif:"MASTER",曲名:"🟣MarbleBlue."},
{ dev:"オンゲキ",con:"15.3",dif:"MASTER",曲名:"🟣光焔のラテラルアーク"},
{ dev:"オンゲキ",con:"15.3",dif:"MASTER",曲名:"🟣MeteorSnow"},
{ dev:"オンゲキ",con:"15.3",dif:"MASTER",曲名:"🟣And Revive The Melody"},
{ dev:"オンゲキ",con:"15.2",dif:"MASTER",曲名:"🟣Regulus"},
{ dev:"オンゲキ",con:"15.2",dif:"MASTER",曲名:"🟣Stardust:RAY"},
{ dev:"オンゲキ",con:"15.1",dif:"MASTER",曲名:"🟣宿星審判"},
{ dev:"オンゲキ",con:"15.1",dif:"MASTER",曲名:"🟣POTENTIAL"},
{ dev:"オンゲキ",con:"15.1",dif:"MASTER",曲名:"🟣雪男"},
{ dev:"オンゲキ",con:"15.1",dif:"MASTER",曲名:"🟣脳天直撃"},
{ dev:"オンゲキ",con:"15.1",dif:"MASTER",曲名:"🟣Magical Panic Adventure"},
{ dev:"オンゲキ",con:"15.1",dif:"MASTER",曲名:"🟣Op.I 《fear-TITΛN-》"},
{ dev:"オンゲキ",con:"15.1",dif:"MASTER",曲名:"🟣Stellar:Dream"},
{ dev:"オンゲキ",con:"15",dif:"MASTER",曲名:"🟣Scythe of Death"},
{ dev:"オンゲキ",con:"15",dif:"MASTER",曲名:"🟣Opfer"},
{ dev:"オンゲキ",con:"15",dif:"MASTER",曲名:"🟣ω4"},
{ dev:"オンゲキ",con:"15",dif:"MASTER",曲名:"🟣AMAZING MIGHTYYYY!!!!"},
{ dev:"オンゲキ",con:"15",dif:"MASTER",曲名:"🟣怨撃"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣MANIERA REMASTERED"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣FREEDOM DiVE"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Invisible Frenzy"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Synthesis."},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣the EmpErroR"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣蜘蛛の糸"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Hainuwele"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Sage"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Titania"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Good bye, Merry-Go-Round."},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Falsum Atlantis."},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Don't Fight The Music"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Viyella's Scream"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Cult future"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣Diamond Dust"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣オンソクデイズ!!"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣GAME：CHANGER"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣THE TRiANGLE"},
{ dev:"オンゲキ",con:"14.9",dif:"MASTER",曲名:"🟣淵底のグレイ・ユークロニア"},
{ dev:"オンゲキ",con:"14.9",dif:"LUNATIC",曲名:"⚪️シリウスの輝きのように"},
{ dev:"オンゲキ",con:"14.9",dif:"LUNATIC",曲名:"⚪️天狗の落とし文 feat.ｙｔｒ"},
{ dev:"オンゲキ",con:"14.9",dif:"LUNATIC",曲名:"⚪️MEGALOVANIA"},
{ dev:"オンゲキ",con:"14.9",dif:"LUNATIC",曲名:"⚪️macrocosmos"},
{ dev:"オンゲキ",con:"14.9",dif:"LUNATIC",曲名:"⚪️GODLINESS"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Re：End of a Dream"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Shamshir -rough Pt.2-"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Crimson Phoenix"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣In Chaos"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Tempestissimo"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Got more raves? -xiRemix-"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣QZKago Requiem"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣TiamaT:F minor"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣YURUSHITE"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Viyella's Tears"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣A Man In The Mirror"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Singularity -technoplanet-"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣Ai C"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣ゼーレンヴァンデルング"},
{ dev:"オンゲキ",con:"14.8",dif:"MASTER",曲名:"🟣しとしとと"},
{ dev:"オンゲキ",con:"14.8",dif:"LUNATIC",曲名:"⚪️My First Phone"},
{ dev:"オンゲキ",con:"14.8",dif:"LUNATIC",曲名:"⚪️Halcyon"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣End Time"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Love & Justice"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣ouroboros -twin stroke of the end-"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣otorii INNOVATED -[i]3-"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣larva"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Xevel"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Last Celebration"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Alea jacta est!"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣渦状銀河のシンフォニエッタ"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Fragrance"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Elemental Ethnic"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣AstrøNotes."},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣FLUFFY FLASH"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Adverse Gaff"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣SUPER AMBULANCE"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣RELOAD"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Final Flash Flight"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣其のエメラルドを見よ"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Buck's Fizz"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣Cogito ergo sum"},
{ dev:"オンゲキ",con:"14.7",dif:"MASTER",曲名:"🟣冥乱幻舞"},
{ dev:"オンゲキ",con:"14.7",dif:"EXPERT",曲名:"🔴Recollect Lines"},
{ dev:"オンゲキ",con:"14.7",dif:"LUNATIC",曲名:"⚪️P！P！P！P！がおー!!"},

]


//別ファイルに送信
exports.song = song;

