//白⚪️,紫🟣,赤🔴,黄🟡,緑🟢
//ゲキだけじゃなくなったけどファイル名変えるのめんどいから放置



let song = [//	{ dev:"オンゲキ", con:, dif:"MASTER", tit:""},
{ dev:"オンゲキ",con:15.7,dif:"MASTER",曲名:"🟣Recollect Lines"},
{ dev:"オンゲキ",con:15.6,dif:"MASTER",曲名:"🟣μ3"},
{ dev:"オンゲキ",con:15.4,dif:"MASTER",曲名:"🟣Apollo"},
{ dev:"オンゲキ",con:15.4,dif:"MASTER",曲名:"🟣LAMIA"},
{ dev:"オンゲキ",con:15.4,dif:"MASTER",曲名:"🟣Selenadia"},
{ dev:"オンゲキ",con:15.4,dif:"MASTER",曲名:"🟣FestA of PandemoniuM"},
{ dev:"オンゲキ",con:15.3,dif:"MASTER",曲名:"🟣MarbleBlue."},
{ dev:"オンゲキ",con:15.3,dif:"MASTER",曲名:"🟣光焔のラテラルアーク"},
{ dev:"オンゲキ",con:15.3,dif:"MASTER",曲名:"🟣MeteorSnow"},
{ dev:"オンゲキ",con:15.3,dif:"MASTER",曲名:"🟣And Revive The Melody"},
{ dev:"オンゲキ",con:15.2,dif:"MASTER",曲名:"🟣Regulus"},
{ dev:"オンゲキ",con:15.2,dif:"MASTER",曲名:"🟣Stardust:RAY"},
{ dev:"オンゲキ",con:15.1,dif:"MASTER",曲名:"🟣宿星審判"},
{ dev:"オンゲキ",con:15.1,dif:"MASTER",曲名:"🟣POTENTIAL"},
{ dev:"オンゲキ",con:15.1,dif:"MASTER",曲名:"🟣雪男"},
{ dev:"オンゲキ",con:15.1,dif:"MASTER",曲名:"🟣脳天直撃"},
{ dev:"オンゲキ",con:15.1,dif:"MASTER",曲名:"🟣Magical Panic Adventure"},
{ dev:"オンゲキ",con:15.1,dif:"MASTER",曲名:"🟣Op.I 《fear-TITΛN-》"},
{ dev:"オンゲキ",con:15.1,dif:"MASTER",曲名:"🟣Stellar:Dream"},
{ dev:"オンゲキ",con:15,dif:"MASTER",曲名:"🟣Scythe of Death"},
{ dev:"オンゲキ",con:15,dif:"MASTER",曲名:"🟣Opfer"},
{ dev:"オンゲキ",con:15,dif:"MASTER",曲名:"🟣ω4"},
{ dev:"オンゲキ",con:15,dif:"MASTER",曲名:"⚪️AMAZING MIGHTYYYY!!!!"},
{ dev:"オンゲキ",con:15,dif:"MASTER",曲名:"⚪️怨撃"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣MANIERA REMASTERED"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣FREEDOM DiVE"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Invisible Frenzy"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Synthesis."},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣the EmpErroR"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣蜘蛛の糸"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Hainuwele"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Sage"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Titania"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Good bye, Merry-Go-Round."},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Falsum Atlantis."},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Don't Fight The Music"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Viyella's Scream"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Cult future"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣Diamond Dust"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣オンソクデイズ!!"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣GAME：CHANGER"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣THE TRiANGLE"},
{ dev:"オンゲキ",con:14.9,dif:"MASTER",曲名:"🟣淵底のグレイ・ユークロニア"},
{ dev:"オンゲキ",con:14.9,dif:"LUNATIC",曲名:"⚪️シリウスの輝きのように"},
{ dev:"オンゲキ",con:14.9,dif:"LUNATIC",曲名:"⚪️天狗の落とし文 feat.ｙｔｒ"},
{ dev:"オンゲキ",con:14.9,dif:"LUNATIC",曲名:"⚪️MEGALOVANIA"},
{ dev:"オンゲキ",con:14.9,dif:"LUNATIC",曲名:"⚪️macrocosmos"},
{ dev:"オンゲキ",con:14.9,dif:"LUNATIC",曲名:"⚪️GODLINESS"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Re：End of a Dream"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Shamshir -rough Pt.2-"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Sparking Revolver"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Crimson Phoenix"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣In Chaos"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Tempestissimo"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Got more raves? -xiRemix-"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣QZKago Requiem"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣TiamaT:F minor"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣YURUSHITE"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Viyella's Tears"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣A Man In The Mirror"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Singularity -technoplanet-"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣Ai C"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣ゼーレンヴァンデルング"},
{ dev:"オンゲキ",con:14.8,dif:"MASTER",曲名:"🟣しとしとと"},
{ dev:"オンゲキ",con:14.8,dif:"LUNATIC",曲名:"⚪️My First Phone"},
{ dev:"オンゲキ",con:14.8,dif:"LUNATIC",曲名:"⚪️Halcyon"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣End Time"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Love & Justice"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣ouroboros -twin stroke of the end-"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣otorii INNOVATED -[i]3-"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣larva"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Xevel"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Last Celebration"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Alea jacta est!"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣渦状銀河のシンフォニエッタ"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Fragrance"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Elemental Ethnic"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣AstrøNotes."},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣FLUFFY FLASH"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Adverse Gaff"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣SUPER AMBULANCE"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣RELOAD"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Final Flash Flight"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣其のエメラルドを見よ"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Buck's Fizz"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣Cogito ergo sum"},
{ dev:"オンゲキ",con:14.7,dif:"MASTER",曲名:"🟣冥乱幻舞"},
{ dev:"オンゲキ",con:14.7,dif:"EXPERT",曲名:"🔴Recollect Lines"},
{ dev:"オンゲキ",con:14.7,dif:"LUNATIC",曲名:"⚪️P！P！P！P！がおー!!"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣ラクガキスト"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣妖々跋扈 ～ Who done it!"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣BATTLE NO.1"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣World Vanquisher"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣Caliburne 〜Story of the Legendary sword〜"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣花と、雪と、ドラムンベース。"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣VIIIbit Explorer"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣MEGATON BLAST"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣GEOMETRIC DANCE"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣心"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣エータ・ベータ・イータ"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣μάγια"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣Diamond Dust -crystal piano Arr.-"},
{ dev:"オンゲキ",con:14.6,dif:"MASTER",曲名:"🟣Prominence"},
{ dev:"オンゲキ",con:14.6,dif:"EXPERT",曲名:"🔴Fragrance"},
{ dev:"オンゲキ",con:14.6,dif:"LUNATIC",曲名:"⚪️luna blu"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣Air"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣Showguts"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣8OROCHI"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣Akasagarbha -reincarnate-"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣怒槌"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣Glorious Crown (tpz over-Over-OVERCUTE REMIX)"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣Climax"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣TEmPTaTiON"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣ハードコア・シンドローム"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣BREaK! BREaK! BREaK!"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣月詠に鳴る"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣N3V3R G3T OV3R"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣Aenbharr"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣ヒトリボッチサテライト"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣MAGNETAR GIRL"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣ミラージュ･フレイグランス"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣FLUFFY FLASH (C-Show & Maozon Remix)"},
{ dev:"オンゲキ",con:14.5,dif:"MASTER",曲名:"🟣Zitronectar"},
{ dev:"オンゲキ",con:14.5,dif:"LUNATIC",曲名:"⚪️Destiny Runner"},
{ dev:"オンゲキ",con:14.5,dif:"LUNATIC",曲名:"⚪️What color..."},
{ dev:"オンゲキ",con:14.5,dif:"LUNATIC",曲名:"⚪️まっすぐ→→→ストリーム！"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Everything Will Freeze"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Armageddon"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Grievous Lady"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Amphisbaena"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣聖者の鼓動"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣MEGALOVANIA"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣10pt8ion"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣雷切 -RAIKIRI-"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣宛城、炎上！！"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Trrricksters!!"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣TECHNOPOLIS 2085"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Starry Colors"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣WE'RE BACK!!"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Blessed Rain"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Desperado Waltz"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣美夜月鏡"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣霧の書斎"},
{ dev:"オンゲキ",con:14.4,dif:"MASTER",曲名:"🟣Baqeela (Creepy Remix)"},
{ dev:"オンゲキ",con:14.4,dif:"LUNATIC",曲名:"⚪️脳漿炸裂ガール"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣3分ガール"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣神威"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Jack-the-Ripper◆"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣DRAGONLADY"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣2112410403927243233368"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣BLUE ZONE"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Malicious Mischance"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Grayed Out-Antifront-"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣混沌を越えし我らが神聖なる調律主を讃えよ"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Garakuta Doll Play"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣folern"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Supersonic Generation"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Galaxy Blaster"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Stargazing Dreamer"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣See The Light"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣ジャンヌ・ダルクの慟哭"},
{ dev:"オンゲキ",con:14.3,dif:"MASTER",曲名:"🟣Starlight★Limited"},
{ dev:"オンゲキ",con:14.3,dif:"EXPERT",曲名:"🔴μ3"},
{ dev:"オンゲキ",con:14.3,dif:"LUNATIC",曲名:"⚪️最終鬼畜全部声"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣あ・り・ま・す・か？"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣初音ミクの激唱"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣Imperishable Night 2006 (2016 Refine)"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣Satori ～3rd EyEs (2020 Recall)"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣U.N.オーエンは彼女なのか？ - Greater Scarlet"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣Sound Chimera"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣Singularity -ETIA-"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣Altale"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣竹"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣音弾超人ゴリライザー"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣PARALLEL★PRISM"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣エンドマークに希望と涙を添えて"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣Genesis"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣PinqPiq (xovevox Remix)"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣B WiZ U"},
{ dev:"オンゲキ",con:14.2,dif:"MASTER",曲名:"🟣Tricky Treat!!!"},
{ dev:"オンゲキ",con:14.2,dif:"LUNATIC",曲名:"⚪️私たち、四季を遊ぶんです！！"},
{ dev:"オンゲキ",con:14.2,dif:"LUNATIC",曲名:"⚪️初音ミクの激唱"},
{ dev:"オンゲキ",con:14.2,dif:"LUNATIC",曲名:"⚪️セガNET麻雀MJ -O.N.G.E.K.I. MIX-"},
{ dev:"オンゲキ",con:14.2,dif:"LUNATIC",曲名:"⚪️トリドリ⇒モリモリ！Lovely fruits☆"},
{ dev:"オンゲキ",con:14.2,dif:"LUNATIC",曲名:"⚪️Transcend Lights"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣カナリア"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣INTERNET YAMERO"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣レータイスパークEx"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣FREEDOM DiVE (tpz Overcute Remix)"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣felys -final remix-"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Singularity -MJ-"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣c.s.q.n."},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Knight Rider"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣SILENT BLUE"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Oshama Scramble! (Cranky Remix)"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Blows Up Everything"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣宙の隣"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Death Scythe"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Daydreama"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣LiftOff"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Daredevil Glaive"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Elusive Emotes"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣Knocking Harder"},
{ dev:"オンゲキ",con:14.1,dif:"MASTER",曲名:"🟣YURUSHITE (LeaF Remix)"},
{ dev:"オンゲキ",con:14.1,dif:"LUNATIC",曲名:"⚪️六兆年と一夜物語"},
{ dev:"オンゲキ",con:14.1,dif:"LUNATIC",曲名:"⚪️ヒバナ"},
{ dev:"オンゲキ",con:14.1,dif:"LUNATIC",曲名:"⚪️Calamity Fortune"},
{ dev:"オンゲキ",con:14.1,dif:"LUNATIC",曲名:"⚪️GranFatalité"},
{ dev:"オンゲキ",con:14.1,dif:"LUNATIC",曲名:"⚪️Rule the World!!"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣ジングルベル"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣宣誓センセーション"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣星界ちゃんと可不ちゃんのおつかい合騒曲"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣きゅうくらりん"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣ナイト・オブ・ナイツ (xi Remix)"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣神々が恋した幻想郷"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣GOODRAGE"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣BBBLOW -rebuild-"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣ENERGY SYNERGY MATRIX"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣7thSense"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣シャッキーーン！！"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣ここからはじまるプロローグ。"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣MUSIC PЯAYER"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣Everlasting Today"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣Dazzle hop"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣R'N'R Monsta"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣GODLINESS"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣ICEBURN"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣Princesses Holiday"},
{ dev:"オンゲキ",con:14,dif:"MASTER",曲名:"🟣Azucar"},
{ dev:"オンゲキ",con:14,dif:"EXPERT",曲名:"🔴光焔のラテラルアーク"},
{ dev:"オンゲキ",con:14,dif:"EXPERT",曲名:"🔴FestA of PandemoniuM"},
{ dev:"オンゲキ",con:14,dif:"LUNATIC",曲名:"⚪️ハッピータイフーン"},
{ dev:"オンゲキ",con:14,dif:"LUNATIC",曲名:"⚪️ロキ"},
{ dev:"オンゲキ",con:14,dif:"LUNATIC",曲名:"⚪️Fly to the Leaden Sky -O.N.G.E.K.I. MIX-"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Seventeen Feels"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣サンダーレスキュー！"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣初音天地開闢神話"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣パラジクロロベンゼン"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣タイガーランペイジ"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣snooze"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣ナイト・オブ・ナイツ (かめりあ's'ワンス・アポン・ア・ナイト'Remix)"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣LUNA DIAL -Version X-SAKUYA-"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣エピトゥリカの祀"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣BABYLON"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Electric Emotion"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Cyaegha"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Lethal Dose"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣閃鋼のブリューナク"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣四月の雨"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣L'epilogue"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣夢花火"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣C & B"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣遺伝子レベル∞スパイラル"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣つっぱれ！にゃんきー魂"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Ai Nov"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Baqeela"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Mini skirt"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Last Kingdom"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Vibes 2k20"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Ai Drew"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Trinity Departure"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Ruler Count, Zero"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣colorful transparency"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Suspiro"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Dramatic…?"},
{ dev:"オンゲキ",con:13.9,dif:"MASTER",曲名:"🟣Livmetarryr"},
{ dev:"オンゲキ",con:13.9,dif:"EXPERT",曲名:"🔴Selenadia"},
{ dev:"オンゲキ",con:13.9,dif:"LUNATIC",曲名:"⚪️ジングルベル"},
{ dev:"オンゲキ",con:13.9,dif:"LUNATIC",曲名:"⚪️ナイト・オブ・ナイツ"},
{ dev:"オンゲキ",con:13.9,dif:"LUNATIC",曲名:"⚪️Here We Go"},
{ dev:"オンゲキ",con:13.9,dif:"LUNATIC",曲名:"⚪️GAME IS LIFE"},
{ dev:"オンゲキ",con:13.9,dif:"LUNATIC",曲名:"⚪️本能的Survivor"},
{ dev:"オンゲキ",con:13.9,dif:"LUNATIC",曲名:"⚪️UTAKATA"},
{ dev:"オンゲキ",con:13.9,dif:"LUNATIC",曲名:"⚪️No Limit RED Force"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣HEAVEN'S RAVE"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣アンチグラビティ・ガール"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣ギガンティックO.T.N"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣撥条少女時計"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣サイハテ"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣卑怯戦隊うろたんだー"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣オートファジー"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Bad Apple!! feat.nomico (Camellia’s “Bad Psy” Remix)"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣断罪は遍く人間の元に"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣スカーレット警察のゲットーパトロール24時"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣conflict"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Duello"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Dreadnought"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Reach for the Stars"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣CO5M1C R4ILR0AD"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣ニニ"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Dement ～after legend～"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣STARLIGHT TWILIGHT -GC edit-"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣YO-KAI Disco"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣with U"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣風仁雷仁"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Summer is over"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Secret Sleuth"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣U ARE"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣足立オウフwwww"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣CHOCOLATE BOMB!!!!"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣We Gonna Party"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣ガチ恋ラビリンス"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Sparkle"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣アマツカミ"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣A Day in the Patisserie"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣最っ高のエンタメだ!!"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Pastel Sprinkles"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣MEGATON BLAST (tpz Overcute Remix)"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣ゲーミングポーラーベア"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Mizutama-Tripster"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣UTOPIA CRASH"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣まりもとおもちゃ箱"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Vibes 2k20 (owl＊aging remix)"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣ロッキンピンクモンスター (豚乙女ランコVoVer.)"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣夢を叶える場所"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Memories of O.N.G.E.K.I."},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣いちげき！のテーマ"},
{ dev:"オンゲキ",con:13.8,dif:"MASTER",曲名:"🟣Apollo -onoken AxSwing Remix-"},
{ dev:"オンゲキ",con:13.8,dif:"EXPERT",曲名:"🔴Scythe of Death"},
{ dev:"オンゲキ",con:13.8,dif:"EXPERT",曲名:"🔴LAMIA"},
{ dev:"オンゲキ",con:13.8,dif:"EXPERT",曲名:"🔴Op.I 《fear-TITΛN-》"},
{ dev:"オンゲキ",con:13.8,dif:"EXPERT",曲名:"🔴Stardust:RAY"},
{ dev:"オンゲキ",con:13.8,dif:"EXPERT",曲名:"🔴And Revive The Melody"},
{ dev:"オンゲキ",con:13.8,dif:"LUNATIC",曲名:"⚪️ネ！コ！"},
{ dev:"オンゲキ",con:13.8,dif:"LUNATIC",曲名:"⚪️空色メモリーズ"},
{ dev:"オンゲキ",con:13.8,dif:"LUNATIC",曲名:"⚪️The world of spirit"},
{ dev:"オンゲキ",con:13.8,dif:"LUNATIC",曲名:"⚪️YO-KAI Disco"},
{ dev:"オンゲキ",con:13.8,dif:"LUNATIC",曲名:"⚪️Perfect Shining!!"},
{ dev:"オンゲキ",con:13.8,dif:"LUNATIC",曲名:"⚪️みんな Happy!!"},
{ dev:"オンゲキ",con:13.8,dif:"LUNATIC",曲名:"⚪️SWEET SHAKE!!"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣藍の華"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣ぶいちゅっばの歌"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣せーので跳べって言ってんの！"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣偉大なる悪魔は実は大天使パトラちゃん様なのだ！"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣カミサマネジマキ"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣クイーンオブハート"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣初音ミクの消失"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣裏表ラバーズ"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣夜咄ディセイブ"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣腐れ外道とチョコレゐト"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣So much loving you★ -DIVA Edit-"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Calamity Fortune"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣ウサテイ"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Doll Judgment"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Destr0yer"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣僕たちの旅とエピローグ。"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Löschen"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Quon"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Oshama Scramble!"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣AMAZING MIGHTYYYY!!!!"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣The wheel to the right"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Imitation:Loud Lounge"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Candy Tall Woman"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Lazy Addiction"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Touch and Go"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣HONEY-Q"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Honey Bear"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣RED to RED"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Lostwizz"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣I got a gig tonight!"},
{ dev:"オンゲキ",con:13.7,dif:"MASTER",曲名:"🟣Event Horizon"},
{ dev:"オンゲキ",con:13.7,dif:"EXPERT",曲名:"🔴Got more raves? -xiRemix-"},
{ dev:"オンゲキ",con:13.7,dif:"EXPERT",曲名:"🔴蜘蛛の糸"},
{ dev:"オンゲキ",con:13.7,dif:"EXPERT",曲名:"🔴Regulus"},
{ dev:"オンゲキ",con:13.7,dif:"EXPERT",曲名:"🔴Apollo"},
{ dev:"オンゲキ",con:13.7,dif:"EXPERT",曲名:"🔴Stellar:Dream"},
{ dev:"オンゲキ",con:13.7,dif:"LUNATIC",曲名:"⚪️Hide & Attack"},
{ dev:"オンゲキ",con:13.7,dif:"LUNATIC",曲名:"⚪️うまぴょい伝説"},
{ dev:"オンゲキ",con:13.7,dif:"LUNATIC",曲名:"⚪️Sakura Fubuki"},
{ dev:"オンゲキ",con:13.7,dif:"LUNATIC",曲名:"⚪️タテマエと本心の大乱闘"},
{ dev:"オンゲキ",con:13.7,dif:"LUNATIC",曲名:"⚪️Starring Stars"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣はっぴぃ にゅう にゃあ"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣インビジブル"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣ジャンキーナイトタウンオーケストラ"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣ド屑"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣ずんだパーリナイ"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Destiny Runner"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣銀のめぐり"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣ナイト・オブ・ナイツ (Cranky Remix)"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣疾走あんさんぶる"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Bad Apple!! feat.nomico (豚乙女 Ver.)"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣アリサのテーマ"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣迷える音色は恋の唄"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Once in my life"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Cutter"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣BOKUTO"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣とびだせ！TO THE COSMIC!!"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣ユメキキョウ"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Rainbow Rush Story"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣居並ぶ穀物と溜息まじりの運送屋"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Maqrite"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Radiance"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣DAWNBREAKER"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣All Right!"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Say Goodbye"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣Random Access Emotions"},
{ dev:"オンゲキ",con:13.6,dif:"MASTER",曲名:"🟣はっぴ〜しゅ〜てぃんぐすた〜"},
{ dev:"オンゲキ",con:13.6,dif:"EXPERT",曲名:"🔴Invisible Frenzy"},
{ dev:"オンゲキ",con:13.6,dif:"EXPERT",曲名:"🔴宿星審判"},
{ dev:"オンゲキ",con:13.6,dif:"EXPERT",曲名:"🔴雪男"},
{ dev:"オンゲキ",con:13.6,dif:"EXPERT",曲名:"🔴Opfer"},
{ dev:"オンゲキ",con:13.6,dif:"EXPERT",曲名:"🔴A Man In The Mirror"},
{ dev:"オンゲキ",con:13.6,dif:"EXPERT",曲名:"🔴Diamond Dust"},
{ dev:"オンゲキ",con:13.6,dif:"LUNATIC",曲名:"⚪️シル・ヴ・プレジデント"},
{ dev:"オンゲキ",con:13.6,dif:"LUNATIC",曲名:"⚪️Zest of Blue"},
{ dev:"オンゲキ",con:13.6,dif:"LUNATIC",曲名:"⚪️どうぶつ☆パラダイス"},
{ dev:"オンゲキ",con:13.6,dif:"LUNATIC",曲名:"⚪️最強 the サマータイム!!!!!"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣Petit Etoile"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣スパッと！スパイ＆スパイス"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣春を告げる"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣モンダイナイトリッパー！"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣アンノウン・マザーグース"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣イカサマライフゲイム"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣幾望の月"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣電脳少女は歌姫の夢を見るか？"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣ヴィラン"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣おひめさまになりたいのッ！"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣妖狐仙楽踏"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣サドマミホリック"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣天狗の落とし文 feat. ｙｔｒ"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣ロストワードクロニカル"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣風に乗せた願い"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣New World"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣花たちに希望を"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣Burning Steel Inferno"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣rePrayer"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣アルカンシエル"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣We Gonna Journey"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣ライトスピード・デイズ"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣ツクヨミステップ"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣STAR"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣Death Doll"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣Jörqer"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣fulgente (flip-side color mix)"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣Catch Me If You Can"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣Butterfly Wave"},
{ dev:"オンゲキ",con:13.5,dif:"MASTER",曲名:"🟣超前進！満点スマイル！"},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴MANIERA REMASTERED"},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴ouroboros -twin stroke of the end-"},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴the EmpErroR"},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴Hainuwele"},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴Singularity -technoplanet-"},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴Magical Panic Adventure"},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴MarbleBlue."},
{ dev:"オンゲキ",con:13.5,dif:"EXPERT",曲名:"🔴しとしとと"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣ヒトガタ"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣INTERNET OVERDOSE"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Lots of love"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣ボッカデラベリタ"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣ストリーミングハート"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣ステラ"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣最終鬼畜妹フランドール・S"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣エピクロスの虹はもう見えない"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Scream out! -音華鏡 Re:BREAK-"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣患部で止まってすぐ溶ける～狂気の優曇華院"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣全力ハッピーライフ"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣物凄い狂っとるフランちゃんが物凄いうた"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Paranoia"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣悪戯センセーション"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣お空のニュークリアフュージョン道場"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣キュアリアス光吉古牌　－祭－"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Over the Border"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Brain Power"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Halcyon"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣ベースラインやってる？笑"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:'🟣Party 4U "holy nite mix"'},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Velaciela (Hyper Mix)"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣ロボットプラネットユートピア"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣福宿音屋魂音泉"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣REAL VOICE"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Paradisoda"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Dolphika"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣Sword of Secret"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣fulgente"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣おやすみのうた"},
{ dev:"オンゲキ",con:13.4,dif:"MASTER",曲名:"🟣いつか花咲くその前に"},
{ dev:"オンゲキ",con:13.4,dif:"EXPERT",曲名:"🔴脳天直撃"},
{ dev:"オンゲキ",con:13.4,dif:"EXPERT",曲名:"🔴Stargazing Dreamer"},
{ dev:"オンゲキ",con:13.4,dif:"EXPERT",曲名:"🔴Don't Fight The Music"},
{ dev:"オンゲキ",con:13.4,dif:"EXPERT",曲名:"🔴Cult future"},
{ dev:"オンゲキ",con:13.4,dif:"EXPERT",曲名:"🔴其のエメラルドを見よ"},
{ dev:"オンゲキ",con:13.4,dif:"EXPERT",曲名:"🔴オンソクデイズ!!"},
{ dev:"オンゲキ",con:13.4,dif:"EXPERT",曲名:"🔴淵底のグレイ・ユークロニア"},
{ dev:"オンゲキ",con:13.4,dif:"LUNATIC",曲名:"⚪️グリーンライツ・セレナーデ"},
{ dev:"オンゲキ",con:13.4,dif:"LUNATIC",曲名:"⚪️夜明けのストリング"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Stage of Star"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Let Me Know (feat. Masayoshi Iimori)"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣君とインフィニティ -2021-"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Goodbye Innocence"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣予感のシグナル"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣人生リセットボタン"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣地球最後の告白を"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ドラマツルギー"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ナンセンス文学"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ワールズエンド・ダンスホール"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣バイオレンストリガー"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ダーリンダンス"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ワーワーワールド"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ミラクルペイント"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣チルノのパーフェクトさんすう教室"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Kattobi KEIKYU Rider"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣キラメケ→Shoot it Now!"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Starlight Disco"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ブツメツビーターズ"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣TAKE ON THE WORLD"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Chelly spLash♪♪"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣オンゲキ全域★アカネサマ？"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣BOUNCE & DANCE"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣撩乱乙女†無双劇"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣YAMINABE☆PANIC ～ご馳走詰め込みフルコース～"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣My precious holiday"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Skip & Smile!!"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣天つ風"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣Island Breeze"},
{ dev:"オンゲキ",con:13.3,dif:"MASTER",曲名:"🟣ヒストリー×ブレイカー"},
{ dev:"オンゲキ",con:13.3,dif:"EXPERT",曲名:"🔴BATTLE NO.1"},
{ dev:"オンゲキ",con:13.3,dif:"EXPERT",曲名:"🔴FREEDOM DiVE"},
{ dev:"オンゲキ",con:13.3,dif:"EXPERT",曲名:"🔴TECHNOPOLIS 2085"},
{ dev:"オンゲキ",con:13.3,dif:"EXPERT",曲名:"🔴Falsum Atlantis."},
{ dev:"オンゲキ",con:13.3,dif:"EXPERT",曲名:"🔴MeteorSnow"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣NEXT COLOR PLANET"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣ハッピーエンドをはじめから"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣ヒステリックナイトガール"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣Time and Space"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣脳漿炸裂ガール"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣ドーナツホール"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣セツナトリップ"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣ラストリゾート"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣しゅわスパ大作戦☆"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣カラッポ・ノンフィクション"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣Alice's Suitcase"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣超常マイマイン"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣コスモポップファンクラブ"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣ロッキンピンクモンスター"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣Heart Cooking Recipe"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣無敵のフロンティア三銃士"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣Geki Geki!! 激闘Break Out!!"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣Resolution"},
{ dev:"オンゲキ",con:13.2,dif:"MASTER",曲名:"🟣夏宵スターマイン"},
{ dev:"オンゲキ",con:13.2,dif:"EXPERT",曲名:"🔴End Time"},
{ dev:"オンゲキ",con:13.2,dif:"EXPERT",曲名:"🔴VIIIbit Explorer"},
{ dev:"オンゲキ",con:13.2,dif:"EXPERT",曲名:"🔴Titania"},
{ dev:"オンゲキ",con:13.2,dif:"EXPERT",曲名:"🔴Viyella's Tears"},
{ dev:"オンゲキ",con:13.2,dif:"EXPERT",曲名:"🔴Viyella's Scream"},
{ dev:"オンゲキ",con:13.2,dif:"EXPERT",曲名:"🔴冥乱幻舞"},
{ dev:"オンゲキ",con:13.2,dif:"LUNATIC",曲名:"⚪️からくりピエロ"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣青春サイダー"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣STORIA"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣Virtual to LIVE"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣シリウスの輝きのように"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣DAYBREAK FRONTLINE"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣デリヘル呼んだら君が来た"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣Seyana. ～何でも言うことを聞いてくれるアカネチャン～"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣吉原ラメント"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣泥の分際で私だけの大切を奪おうだなんて"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣敗北の少年"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣ケロ⑨destiny"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣Äventyr"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣Gate of Doom"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣天火明命"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣Paqqin"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣Cosmic Train"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣UTAKATA"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:'🟣ludicium "Apocalypsis Mix"'},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣ウキウキ☆Candy!"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣反撃! 突撃! Back To Back!"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣give it up to you"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣シンデレラディスコ"},
{ dev:"オンゲキ",con:13.1,dif:"MASTER",曲名:"🟣花時は夢を見る。"},
{ dev:"オンゲキ",con:13.1,dif:"EXPERT",曲名:"🔴Shamshir -rough Pt.2-"},
{ dev:"オンゲキ",con:13.1,dif:"EXPERT",曲名:"🔴TiamaT:F minor"},
{ dev:"オンゲキ",con:13.1,dif:"EXPERT",曲名:"🔴FLUFFY FLASH"},
{ dev:"オンゲキ",con:13.1,dif:"EXPERT",曲名:"🔴ジャンヌ・ダルクの慟哭"},
{ dev:"オンゲキ",con:13.1,dif:"EXPERT",曲名:"🔴GAME:CHANGER"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣クライノイド"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣月影のトロイメライ"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣幸せになれる隠しコマンドがあるらしい"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣アンハッピーリフレイン"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣スクランブル交際"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣アカリがやってきたぞっ"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣ネクストネスト"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣Ready Steady"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣sweet little sister"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣サクライロフワリ"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣Change Our MIRAI！（Our 7 Lights）"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣Magic"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣はちみつアドベンチャー"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣TeA"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣本能的 Survivor"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣MAKING！ハイタッチ！"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣感情アクセラレイション"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣ぱくぱく☆がーる"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣Glitter-Glitter"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣HEADLINER"},
{ dev:"オンゲキ",con:13,dif:"MASTER",曲名:"🟣Individual on parade!"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴Crimson Phoenix"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴Synthesis."},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴混沌を越えし我らが神聖なる調律主を讃えよ"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴Garakuta Doll Play"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴QZKago Requiem"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴POTENTIAL"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴Sage"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴MEGATON BLAST"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴ω4"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴美夜月鏡"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴Ai C"},
{ dev:"オンゲキ",con:13,dif:"EXPERT",曲名:"🔴Cogito ergo sum"},


{ dev:"maimai",con:15,dif:"ReMAS",type:"でらっくす",曲名:"⚪️系ぎて"},
{ dev:"maimai",con:15,dif:"ReMAS",type:"スタンダード",曲名:"⚪️PANDORA PARADOXXX"},
{ dev:"maimai",con:14.9,dif:"MAS",type:"でらっくす",曲名:"🟣躯樹の墓守"},
{ dev:"maimai",con:14.9,dif:"MAS",type:"でらっくす",曲名:"🟣sølips"},
{ dev:"maimai",con:14.9,dif:"MAS",type:"でらっくす",曲名:"🟣World's end loneliness"},
{ dev:"maimai",con:14.9,dif:"MAS",type:"でらっくす",曲名:"🟣Latent Kingdom"},
{ dev:"maimai",con:14.9,dif:"MAS",type:"でらっくす",曲名:"🟣raputa"},
{ dev:"maimai",con:14.9,dif:"ReMAS",type:"スタンダード",曲名:"⚪️QZKago Requiem"},
{ dev:"maimai",con:14.9,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Schwarzschild"},
{ dev:"maimai",con:14.9,dif:"ReMAS",type:"スタンダード",曲名:"⚪️the EmpErroR"},
{ dev:"maimai",con:14.9,dif:"MAS",type:"スタンダード",曲名:"🟣PANDORA PARADOXXX"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"でらっくす",曲名:"🟣封焔の135秒"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"でらっくす",曲名:"🟣Heavenly Blast"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"でらっくす",曲名:"🟣VeRForTe αRtE:VEiN"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"でらっくす",曲名:"🟣Straight into the lights"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"でらっくす",曲名:"🟣系ぎて"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"でらっくす",曲名:"🟣ℝ∈Χ LUNATiCA"},
{ dev:"maimai",con:14.8,dif:"ReMAS",type:"スタンダード",曲名:"⚪️In Chaos"},
{ dev:"maimai",con:14.8,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Garakuta Doll Play"},
{ dev:"maimai",con:14.8,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Alea jacta est!"},
{ dev:"maimai",con:14.8,dif:"ReMAS",type:"スタンダード",曲名:"⚪️雷切-RAIKIRI-"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣怒槌"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣Glorious Crown"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣Our Wrenally"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣Excalibur ～Revived Resolution～"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣larva"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣SILENT BLUE"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣QZKago Requiem"},
{ dev:"maimai",con:14.8,dif:"MAS",type:"スタンダード",曲名:"🟣the EmpErroR"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣IF:U"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣Λzure Vixen"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣LAMIA"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣Apollo"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣ジングルベル"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣TEmPTaTiON"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣Valsqotch"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣Regulus"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣BREaK! BREaK! BREaK!"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣VIIIbit Explorer"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣Lia=Fail"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣GIGANTØMAKHIA"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣チューリングの跡"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣WiPE OUT MEMORIES"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣Metamorphosism"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣康莊大道"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣超熊猫的周遊記(ワンダーパンダートラベラー)"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"でらっくす",曲名:"🟣KHYMΞXΛ"},
{ dev:"maimai",con:14.7,dif:"ReMAS",type:"スタンダード",曲名:"⚪️ガラテアの螺旋"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"スタンダード",曲名:"🟣End Time"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"スタンダード",曲名:"🟣AMAZING MIGHTYYYY!!!!"},
{ dev:"maimai",con:14.7,dif:"MAS",type:"スタンダード",曲名:"🟣雷切-RAIKIRI-"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣Re:Unknown X"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣神威"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣Titania"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣脳天直撃"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣渦状銀河のシンフォニエッタ"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣AMABIE"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣BLACK SWAN"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣Yorugao"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣mystique as iris"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣ViRTUS"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"でらっくす",曲名:"🟣VERTeX (rintaro soma deconstructed remix)"},
{ dev:"maimai",con:14.6,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Fragrance"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"スタンダード",曲名:"🟣Ignis Danse"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"スタンダード",曲名:"🟣TiamaT:F minor"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"スタンダード",曲名:"🟣ガラテアの螺旋"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"スタンダード",曲名:"🟣VERTeX"},
{ dev:"maimai",con:14.6,dif:"MAS",type:"スタンダード",曲名:"🟣Prophesy One"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Bloody Trail"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣QUATTUORUX"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣RondeauX of RagnaroQ"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣最強STRONGER"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Sage"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣初音ミクの消失"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣BATTLE NO.1"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Aegleseeker"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣PUPA"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Falsum Atlantis."},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣otorii INNOVATED -[i]3-"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣アポカリプスに反逆の焔を焚べろ"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣BIRTH"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Sqlupp (Camellia's 'Sqleipd*Hiytex' Remix)"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Raven Emperor"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Strive against fate"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"でらっくす",曲名:"🟣Rising on the horizon"},
{ dev:"maimai",con:14.5,dif:"ReMAS",type:"スタンダード",曲名:"⚪️源平大戦絵巻テーマソング"},
{ dev:"maimai",con:14.5,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Beat of getting entangled"},
{ dev:"maimai",con:14.5,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Dragoon"},
{ dev:"maimai",con:14.5,dif:"ReMAS",type:"スタンダード",曲名:"⚪️AMAZING MIGHTYYYY!!!!"},
{ dev:"maimai",con:14.5,dif:"ReMAS",type:"スタンダード",曲名:"⚪️FFT"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣初音ミクの激唱"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣FUJIN Rumble"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣Credits"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣Axeria"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣Oshama Scramble!"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣CITRUS MONSTER"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣ねぇ、壊れタ人形ハ何処へ棄テらレるノ？"},
{ dev:"maimai",con:14.5,dif:"MAS",type:"スタンダード",曲名:"🟣VIIIbit Explorer"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣MarbleBlue."},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣QuiQ"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣ouroboros -twin stroke of the end-"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣felys -final remix-"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣Re：End of a Dream"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣CO5M1C R4ILR0AD"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣Mjölnir"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣天使光輪"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣YURUSHITE"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣スピカの天秤"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣Trrricksters!!"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣FLUFFY FLASH"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣GEOMETRIC DANCE"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣UniTas"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣ARAIS"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:'🟣≠彡"/了→'},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣ほしぞらスペクタクル"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣U&iVERSE -銀河鸞翔-"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣Trick tear"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣#狂った民族２ PRAVARGYAZOOQA"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣VSpook!"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"でらっくす",曲名:"🟣Energizing Flame"},
{ dev:"maimai",con:14.4,dif:"ReMAS",type:"でらっくす",曲名:"⚪️バーチャルダム　ネーション"},
{ dev:"maimai",con:14.4,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Revive The Rave"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"スタンダード",曲名:"🟣極圏"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"スタンダード",曲名:"🟣MYTHOS"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"スタンダード",曲名:'🟣System "Z"'},
{ dev:"maimai",con:14.4,dif:"MAS",type:"スタンダード",曲名:"🟣Contrapasso -paradiso-"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"スタンダード",曲名:"🟣7thSense"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"スタンダード",曲名:"🟣Moon of Noon"},
{ dev:"maimai",con:14.4,dif:"MAS",type:"スタンダード",曲名:"🟣Alea jacta est!"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣DEVOTION"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣Cthugha"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣田中"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣Climax"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣MEGATON BLAST"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣宿星審判"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣SUPER AMBULANCE"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣電光石火"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣Hainuwele"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣SQUAD -Phvntom-"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣STEEL TRANSONIC"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣Xenovcipher"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣N3V3R G3T OV3R"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣Swift Swing"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣“411Ψ892”"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣地球"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"でらっくす",曲名:"🟣Party☆People☆Princess"},
{ dev:"maimai",con:14.3,dif:"ReMAS",type:"でらっくす",曲名:"⚪️Blows Up Everything"},
{ dev:"maimai",con:14.3,dif:"ReMAS",type:"スタンダード",曲名:"⚪️ナイト・オブ・ナイツ"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣Halcyon"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣エンドマークに希望と涙を添えて"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣World Vanquisher"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣Xevel"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣ジングルベル"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣Caliburne ～Story of the Legendary sword～"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣Aiolos"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣HERA"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣Panopticon"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣花と、雪と、ドラムンベース。"},
{ dev:"maimai",con:14.3,dif:"MAS",type:"スタンダード",曲名:"🟣渦状銀河のシンフォニエッタ"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣ミラクルポップ☆アドベンチャー!!!!!"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣勦滅"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣デッドマンズバラッド"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣Maboroshi"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣竹"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣BULK UP (GAME EXCLUSIVE EDIT)"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣Desperado Waltz"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣蜘蛛の糸"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣インパアフェクシオン・ホワイトガアル"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣チエルカ／エソテリカ"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"でらっくす",曲名:"🟣NAGAREBOSHI☆ROCKET"},
{ dev:"maimai",con:14.2,dif:"ReMAS",type:"でらっくす",曲名:"⚪️MAXRAGE"},
{ dev:"maimai",con:14.2,dif:"ReMAS",type:"スタンダード",曲名:"⚪️ロストワンの号哭"},
{ dev:"maimai",con:14.2,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Beat Of Mind"},
{ dev:"maimai",con:14.2,dif:"ReMAS",type:"スタンダード",曲名:"⚪️FLOWER"},
{ dev:"maimai",con:14.2,dif:"ReMAS",type:"スタンダード",曲名:"⚪️ジングルベル"},
{ dev:"maimai",con:14.2,dif:"ReMAS",type:"スタンダード",曲名:"⚪️記憶、記録"},
{ dev:"maimai",con:14.2,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Death Scythe"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣Calamity Fortune"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣きたさいたま2000"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣conflict"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣Scarlet Lance"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣B.M.S."},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣Destr0yer"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣Fragrance"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣Garakuta Doll Play"},
{ dev:"maimai",con:14.2,dif:"MAS",type:"スタンダード",曲名:"🟣Schwarzschild"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣Grievous Lady"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣BLUE ZONE"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣Love’s Theme of BADASS ～バッド・アス 愛のテーマ～"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣Good bye, Merry-Go-Round."},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣エータ・ベータ・イータ"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣Don't Fight The Music"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣HECATONCHEIR"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"でらっくす",曲名:"🟣The Great Banquet"},
{ dev:"maimai",con:14.1,dif:"ReMAS",type:"スタンダード",曲名:"⚪️Panopticon"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"スタンダード",曲名:"🟣麒麟"},
{ dev:"maimai",con:14.1,dif:"MAS",type:"スタンダード",曲名:"🟣Ragnarok"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣INFiNiTE ENERZY -Overdoze-"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Destiny Runner"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Luminaria"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣エナドリおいしいソング"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣僕の和風本当上手"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣ULTRA SYNERGY MATRIX"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Vallista"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣WE'RE BACK!!"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣火炎地獄"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Mutation"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣ワンダーシャッフェンの法則"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Starry Colors"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣星詠みとデスペラード"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Alcyone"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣パラマウント☆ショータイム！！"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Tricolor⁂circuS"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Beat Opera op.1"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣ツムギボシ"},
{ dev:"maimai",con:14,dif:"MAS",type:"でらっくす",曲名:"🟣Horoscope Express"},
{ dev:"maimai",con:14,dif:"ReMAS",type:"でらっくす",曲名:"⚪️一か罰"},
{ dev:"maimai",con:14,dif:"ReMAS",type:"でらっくす",曲名:"⚪️Now or Never"},
{ dev:"maimai",con:14,dif:"ReMAS",type:"スタンダード",曲名:"⚪️カゲロウデイズ"},
{ dev:"maimai",con:14,dif:"ReMAS",type:"スタンダード",曲名:"⚪️患部で止まってすぐ溶ける～狂気の優曇華院"},
{ dev:"maimai",con:14,dif:"ReMAS",type:"スタンダード",曲名:'⚪️System "Z"'},
{ dev:"maimai",con:14,dif:"ReMAS",type:"スタンダード",曲名:"⚪️FEEL the BEATS"},
{ dev:"maimai",con:14,dif:"ReMAS",type:"スタンダード",曲名:"⚪️アージェントシンメトリー"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣脳漿炸裂ガール"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣幸せになれる隠しコマンドがあるらしい"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣ウサテイ"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣幻想のサテライト"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Scream out! -maimai SONIC WASHER Edit-"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣もうみんなしねばいいのに"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Like the Wind [Reborn]"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Outlaw's Lullaby"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Jack-the-Ripper◆"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣DRAGONLADY"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣B.B.K.K.B.K.K."},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Got more raves?"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣METATRON"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣夜明けまであと３秒"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣GO BACK 2 YOUR RAVE"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Maxi"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣人里に下ったアタイがいつの間にか社畜になっていた件"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣FREEDOM DiVE(tpz Overcute Remix)"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣魔法少女になるしかねぇ"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣The wheel to the right"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Nerverakes"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣火炎地獄"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Lividi"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Jumble Rumble"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Nitrous Fury"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣天火明命"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣分からない"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣KING is BACK!!"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Ultranova"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣Justified"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣keep hopping"},
{ dev:"maimai",con:14,dif:"MAS",type:"スタンダード",曲名:"🟣FFT"},

]


//別ファイルに送信
exports.song = song;

